/**
 * Clawdra Connectors Registry
 * ALL connectors from Claude's connector catalog
 * Each connector has config, capabilities, and MCP integration details
 */

export interface ConnectorEntry {
  id: string;
  name: string;
  description: string;
  category: ConnectorCategory;
  envVars: string[];
  mcpPackage?: string;
  restApi?: string;
  capabilities: string[];
  interactive: boolean;
  official: boolean;
}

export type ConnectorCategory =
  | "database" | "deploy" | "email" | "cms" | "hosting" | "auth" | "search" | "ui" | "devops"
  | "crm" | "marketing" | "finance" | "analytics" | "communication" | "project-management"
  | "design" | "code" | "security" | "monitoring" | "storage" | "ai-ml" | "legal"
  | "healthcare" | "blockchain" | "events" | "hr" | "sales" | "support" | "ecommerce"
  | "data-platform" | "observability" | "automation" | "social" | "research" | "travel"
  | "music" | "media" | "productivity" | "knowledge" | "biotech" | "government";

export const ALL_CONNECTORS: ConnectorEntry[] = [
  // ============================================
  // DATABASE & BACKEND
  // ============================================
  {
    id: "supabase",
    name: "Supabase",
    description: "Manage databases, authentication, and storage",
    category: "database",
    envVars: ["SUPABASE_URL", "SUPABASE_KEY"],
    mcpPackage: "@modelcontextprotocol/server-postgres",
    capabilities: ["database", "auth", "storage", "realtime", "edge-functions"],
    interactive: true,
    official: true,
  },
  {
    id: "firebase",
    name: "Firebase",
    description: "Access Firestore, Auth, Functions, Storage",
    category: "database",
    envVars: ["FIREBASE_PROJECT_ID", "FIREBASE_CLIENT_EMAIL", "FIREBASE_PRIVATE_KEY"],
    capabilities: ["firestore", "auth", "functions", "storage", "hosting"],
    interactive: true,
    official: true,
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Query and manage PostgreSQL databases",
    category: "database",
    envVars: ["POSTGRES_URL"],
    mcpPackage: "@modelcontextprotocol/server-postgres",
    capabilities: ["query", "schema", "migrations"],
    interactive: false,
    official: true,
  },
  {
    id: "sqlite",
    name: "SQLite",
    description: "Query and manage SQLite databases",
    category: "database",
    envVars: ["SQLITE_PATH"],
    mcpPackage: "@modelcontextprotocol/server-sqlite",
    capabilities: ["query", "schema"],
    interactive: false,
    official: true,
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "Query and manage MongoDB collections",
    category: "database",
    envVars: ["MONGODB_URI"],
    capabilities: ["query", "aggregation", "indexes"],
    interactive: false,
    official: false,
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "Query and manage MySQL databases",
    category: "database",
    envVars: ["MYSQL_URL"],
    capabilities: ["query", "schema"],
    interactive: false,
    official: false,
  },
  {
    id: "databricks",
    name: "Databricks",
    description: "Managed MCP servers with Unity Catalog and Mosaic AI",
    category: "data-platform",
    envVars: ["DATABRICKS_HOST", "DATABRICKS_TOKEN"],
    capabilities: ["unity-catalog", "mosaic-ai", "notebooks", "jobs"],
    interactive: false,
    official: true,
  },
  {
    id: "snowflake",
    name: "Snowflake",
    description: "Retrieve both structured and unstructured data",
    category: "data-platform",
    envVars: ["SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USERNAME", "SNOWFLAKE_PASSWORD"],
    capabilities: ["query", "warehouse", "data-share"],
    interactive: false,
    official: true,
  },
  {
    id: "motherduck",
    name: "MotherDuck",
    description: "Get answers from your data",
    category: "data-platform",
    envVars: ["MOTHERDUCK_TOKEN"],
    capabilities: ["query", "duckdb"],
    interactive: false,
    official: true,
  },
  {
    id: "dremio",
    name: "Dremio Cloud",
    description: "Analyze and get insights from your lakehouse data",
    category: "data-platform",
    envVars: ["DREMIO_TOKEN", "DREMIO_ENDPOINT"],
    capabilities: ["query", "lakehouse"],
    interactive: false,
    official: true,
  },
  {
    id: "starburst",
    name: "Starburst",
    description: "Securely retrieve data from your federated data sources",
    category: "data-platform",
    envVars: ["STARBURST_HOST", "STARBURST_TOKEN"],
    capabilities: ["query", "federated"],
    interactive: false,
    official: true,
  },
  {
    id: "planet-scale",
    name: "PlanetScale",
    description: "Authenticated access to your Postgres and MySQL DB's",
    category: "database",
    envVars: ["PLANETSCALE_TOKEN"],
    capabilities: ["query", "branch", "deploy"],
    interactive: false,
    official: true,
  },
  {
    id: "bigquery",
    name: "Google Cloud BigQuery",
    description: "BigQuery: Advanced analytical insights for agents",
    category: "data-platform",
    envVars: ["GOOGLE_APPLICATION_CREDENTIALS"],
    capabilities: ["query", "analytics"],
    interactive: false,
    official: true,
  },
  {
    id: "hex",
    name: "Hex",
    description: "Answer questions with the Hex agent",
    category: "analytics",
    envVars: ["HEX_API_KEY"],
    capabilities: ["query", "charts"],
    interactive: true,
    official: true,
  },
  {
    id: "metabase",
    name: "Metabase",
    description: "A high-performance MCP server for Metabase analytics data access",
    category: "analytics",
    envVars: ["METABASE_URL", "METABASE_API_KEY"],
    capabilities: ["query", "dashboard"],
    interactive: false,
    official: true,
  },
  {
    id: "tableau",
    name: "Tableau",
    description: "Helping agents see and understand data",
    category: "analytics",
    envVars: ["TABLEAU_SERVER", "TABLEAU_TOKEN"],
    capabilities: ["dashboard", "viz"],
    interactive: false,
    official: true,
  },

  // ============================================
  // DEPLOY & HOSTING
  // ============================================
  {
    id: "vercel",
    name: "Vercel",
    description: "Analyze, debug, and manage projects and deployments",
    category: "deploy",
    envVars: ["VERCEL_TOKEN"],
    mcpPackage: "@vercel/mcp",
    capabilities: ["deploy", "logs", "domains", "env-vars"],
    interactive: true,
    official: true,
  },
  {
    id: "netlify",
    name: "Netlify",
    description: "Create, deploy, manage, and secure websites on Netlify",
    category: "deploy",
    envVars: ["NETLIFY_TOKEN"],
    capabilities: ["deploy", "sites", "functions"],
    interactive: true,
    official: true,
  },
  {
    id: "cloudflare",
    name: "Cloudflare Developer Platform",
    description: "Build applications with compute, storage, and AI",
    category: "hosting",
    envVars: ["CLOUDFLARE_API_TOKEN"],
    capabilities: ["workers", "kv", "r2", "d1", "ai"],
    interactive: false,
    official: true,
  },
  {
    id: "hostinger",
    name: "Hostinger",
    description: "Manage hosting, domains, DNS, email accounts, databases",
    category: "hosting",
    envVars: ["HOSTINGER_API_KEY", "HOSTINGER_API_SECRET"],
    capabilities: ["hosting", "dns", "email", "database"],
    interactive: false,
    official: false,
  },
  {
    id: "wix",
    name: "Wix",
    description: "Manage and build sites and apps on Wix",
    category: "hosting",
    envVars: ["WIX_API_KEY"],
    capabilities: ["sites", "cms", "ecommerce"],
    interactive: true,
    official: true,
  },
  {
    id: "webflow",
    name: "Webflow",
    description: "Manage Webflow CMS, pages, assets and sites",
    category: "hosting",
    envVars: ["WEBFLOW_TOKEN"],
    capabilities: ["cms", "pages", "assets"],
    interactive: false,
    official: true,
  },
  {
    id: "wordpress-com",
    name: "WordPress.com",
    description: "Secure AI access to manage your WordPress.com sites",
    category: "cms",
    envVars: ["WORDPRESS_TOKEN"],
    capabilities: ["posts", "pages", "media"],
    interactive: true,
    official: true,
  },

  // ============================================
  // CRM & SALES
  // ============================================
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Chat with your CRM data to get personalized insights",
    category: "crm",
    envVars: ["HUBSPOT_API_KEY"],
    capabilities: ["contacts", "deals", "companies", "tickets"],
    interactive: true,
    official: true,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Access Salesforce CRM data and records",
    category: "crm",
    envVars: ["SALESFORCE_TOKEN", "SALESFORCE_INSTANCE_URL"],
    capabilities: ["query", "records", "search"],
    interactive: true,
    official: true,
  },
  {
    id: "attio",
    name: "Attio",
    description: "Search, manage, and update your Attio CRM from Claude",
    category: "crm",
    envVars: ["ATTIO_API_KEY"],
    capabilities: ["records", "lists", "notes"],
    interactive: true,
    official: true,
  },
  {
    id: "close-crm",
    name: "Close",
    description: "Connect Claude to Close CRM to securely access and act on your sales data",
    category: "crm",
    envVars: ["CLOSE_API_KEY"],
    capabilities: ["leads", "contacts", "opportunities"],
    interactive: false,
    official: true,
  },
  {
    id: "zoho-crm",
    name: "Zoho CRM",
    description: "MCP Server for Zoho CRM Workflows",
    category: "crm",
    envVars: ["ZOHO_CLIENT_ID", "ZOHO_CLIENT_SECRET"],
    capabilities: ["leads", "contacts", "deals"],
    interactive: false,
    official: true,
  },
  {
    id: "apollo",
    name: "Apollo.io",
    description: "Prospect, enrich leads, and load outreach sequences",
    category: "sales",
    envVars: ["APOLLO_API_KEY"],
    capabilities: ["prospects", "enrichment", "sequences"],
    interactive: false,
    official: true,
  },
  {
    id: "zoominfo",
    name: "ZoomInfo",
    description: "Enrich contacts & accounts with GTM intelligence",
    category: "sales",
    envVars: ["ZOOMINFO_API_KEY"],
    capabilities: ["enrichment", "search"],
    interactive: false,
    official: true,
  },
  {
    id: "clarify-crm",
    name: "Clarify",
    description: "Query your CRM. Create records. Ask anything.",
    category: "crm",
    envVars: ["CLARIFY_API_KEY"],
    capabilities: ["query", "records"],
    interactive: false,
    official: true,
  },
  {
    id: "customer-io",
    name: "Customer.io",
    description: "Explore customer data and generate insights via Claude",
    category: "analytics",
    envVars: ["CUSTOMERIO_API_KEY"],
    capabilities: ["profiles", "campaigns"],
    interactive: false,
    official: true,
  },

  // ============================================
  // COMMUNICATION
  // ============================================
  {
    id: "slack",
    name: "Slack",
    description: "Send messages, create canvases, and fetch Slack data",
    category: "communication",
    envVars: ["SLACK_BOT_TOKEN", "SLACK_APP_TOKEN"],
    mcpPackage: "@modelcontextprotocol/server-slack",
    capabilities: ["messages", "channels", "users", "threads"],
    interactive: true,
    official: true,
  },
  {
    id: "gmail",
    name: "Gmail",
    description: "Draft replies, summarize threads, & search your inbox",
    category: "communication",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"],
    capabilities: ["read", "send", "search", "labels"],
    interactive: true,
    official: true,
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Manage your schedule and coordinate meetings effortlessly",
    category: "productivity",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"],
    capabilities: ["events", "calendar", "availability"],
    interactive: true,
    official: true,
  },
  {
    id: "resend",
    name: "Resend",
    description: "Email API for developers. Send, track, and manage emails.",
    category: "email",
    envVars: ["RESEND_API_KEY"],
    capabilities: ["send", "templates", "contacts"],
    interactive: false,
    official: true,
  },
  {
    id: "mailerlite",
    name: "MailerLite",
    description: "Turn Claude into your email marketing assistant",
    category: "email",
    envVars: ["MAILERLITE_API_KEY"],
    capabilities: ["campaigns", "subscribers", "groups"],
    interactive: false,
    official: true,
  },
  {
    id: "mailchimp",
    name: "Intuit Mailchimp",
    description: "Create marketing campaigns",
    category: "email",
    envVars: ["MAILCHIMP_API_KEY"],
    capabilities: ["campaigns", "audiences"],
    interactive: true,
    official: true,
  },
  {
    id: "mailtrap",
    name: "Mailtrap",
    description: "Send emails and manage templates using Mailtrap",
    category: "email",
    envVars: ["MAILTRAP_API_KEY"],
    capabilities: ["send", "templates"],
    interactive: false,
    official: true,
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    description: "Report, strategize & create with real-time Klaviyo data",
    category: "marketing",
    envVars: ["KLAVIYO_API_KEY"],
    capabilities: ["profiles", "campaigns", "flows"],
    interactive: true,
    official: true,
  },
  {
    id: "activecampaign",
    name: "ActiveCampaign",
    description: "Autonomous marketing to transform how you work",
    category: "marketing",
    envVars: ["ACTIVECAMPAIGN_API_KEY"],
    capabilities: ["contacts", "deals", "automations"],
    interactive: false,
    official: true,
  },
  {
    id: "intercom",
    name: "Intercom",
    description: "Access to Intercom data for better customer insights",
    category: "support",
    envVars: ["INTERCOM_TOKEN"],
    capabilities: ["conversations", "contacts", "articles"],
    interactive: false,
    official: true,
  },
  {
    id: "outreach",
    name: "Outreach",
    description: "Unleash your team's best performance with Outreach AI",
    category: "sales",
    envVars: ["OUTREACH_API_KEY"],
    capabilities: ["prospects", "sequences", "mailings"],
    interactive: false,
    official: true,
  },
  {
    id: "ifttt",
    name: "IFTTT",
    description: "Connect, control, and automate 1,000+ apps with IFTTT",
    category: "automation",
    envVars: ["IFTTT_API_KEY"],
    capabilities: ["applets", "webhooks"],
    interactive: true,
    official: true,
  },
  {
    id: "zapier",
    name: "Zapier",
    description: "Automate workflows across thousands of apps via conversation",
    category: "automation",
    envVars: ["ZAPIER_API_KEY"],
    capabilities: ["zaps", "actions"],
    interactive: true,
    official: true,
  },
  {
    id: "make",
    name: "Make",
    description: "Run Make scenarios and manage your Make account",
    category: "automation",
    envVars: ["MAKE_API_TOKEN"],
    capabilities: ["scenarios", "executions"],
    interactive: false,
    official: true,
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Access and run your n8n workflows",
    category: "automation",
    envVars: ["N8N_API_KEY"],
    capabilities: ["workflows", "executions"],
    interactive: false,
    official: true,
  },
  {
    id: "workato",
    name: "Workato",
    description: "Automate workflows and connect your business apps",
    category: "automation",
    envVars: ["WORKATO_TOKEN"],
    capabilities: ["recipes", "jobs"],
    interactive: false,
    official: true,
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    description: "Manage incidents, services and on-call schedules",
    category: "monitoring",
    envVars: ["PAGERDUTY_API_TOKEN"],
    capabilities: ["incidents", "services", "schedules"],
    interactive: false,
    official: true,
  },

  // ============================================
  // PROJECT MANAGEMENT
  // ============================================
  {
    id: "linear",
    name: "Linear",
    description: "Manage issues, projects & team workflows in Linear",
    category: "project-management",
    envVars: ["LINEAR_API_KEY"],
    capabilities: ["issues", "projects", "teams"],
    interactive: true,
    official: true,
  },
  {
    id: "jira",
    name: "Atlassian Rovo",
    description: "Access Jira & Confluence from Claude",
    category: "project-management",
    envVars: ["JIRA_TOKEN", "CONFLUENCE_TOKEN"],
    capabilities: ["issues", "projects", "pages"],
    interactive: true,
    official: true,
  },
  {
    id: "asana",
    name: "Asana",
    description: "Connect to Asana to coordinate tasks, projects, and goals",
    category: "project-management",
    envVars: ["ASANA_TOKEN"],
    capabilities: ["tasks", "projects", "goals"],
    interactive: true,
    official: true,
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "Project management & collaboration for teams & agents",
    category: "project-management",
    envVars: ["CLICKUP_TOKEN"],
    capabilities: ["tasks", "lists", "spaces"],
    interactive: true,
    official: true,
  },
  {
    id: "monday",
    name: "monday.com",
    description: "Manage projects, boards, and workflows in monday.com",
    category: "project-management",
    envVars: ["MONDAY_API_KEY"],
    capabilities: ["boards", "items", "groups"],
    interactive: true,
    official: true,
  },
  {
    id: "smartsheet",
    name: "Smartsheet",
    description: "Analyze and manage Smartsheet data with Claude",
    category: "project-management",
    envVars: ["SMARTSHEET_TOKEN"],
    capabilities: ["sheets", "rows"],
    interactive: false,
    official: true,
  },
  {
    id: "devrev",
    name: "DevRev",
    description: "Search and update your company's knowledge graph",
    category: "project-management",
    envVars: ["DEVREV_PAT"],
    capabilities: ["search", "works", "parts"],
    interactive: false,
    official: true,
  },
  {
    id: "zoho-projects",
    name: "Zoho Projects",
    description: "Zoho Projects MCP for Task & Project Automation",
    category: "project-management",
    envVars: ["ZOHO_CLIENT_ID", "ZOHO_CLIENT_SECRET"],
    capabilities: ["tasks", "projects"],
    interactive: false,
    official: true,
  },
  {
    id: "process-street",
    name: "Process Street",
    description: "Explore and update your Process Street data",
    category: "project-management",
    envVars: ["PROCESS_STREET_API_KEY"],
    capabilities: ["workflows", "checklists"],
    interactive: false,
    official: true,
  },

  // ============================================
  // CODE & DEVELOPMENT
  // ============================================
  {
    id: "github",
    name: "GitHub",
    description: "Repos, issues, PRs, actions, packages. Full GitOps workflow.",
    category: "code",
    envVars: ["GITHUB_TOKEN"],
    mcpPackage: "@modelcontextprotocol/server-github",
    capabilities: ["repos", "issues", "prs", "actions", "packages"],
    interactive: true,
    official: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Access GitLab repos, issues, merge requests, CI/CD",
    category: "code",
    envVars: ["GITLAB_TOKEN"],
    capabilities: ["repos", "issues", "mrs", "pipelines"],
    interactive: false,
    official: false,
  },
  {
    id: "postman",
    name: "Postman",
    description: "Give API context to your coding agents",
    category: "code",
    envVars: ["POSTMAN_API_KEY"],
    capabilities: ["collections", "apis"],
    interactive: false,
    official: true,
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Search, query, and debug errors intelligently",
    category: "monitoring",
    envVars: ["SENTRY_AUTH_TOKEN"],
    capabilities: ["errors", "releases", "projects"],
    interactive: false,
    official: true,
  },
  {
    id: "stytch",
    name: "Stytch",
    description: "Manage your Stytch Project",
    category: "auth",
    envVars: ["STYTCH_PROJECT_ID", "STYTCH_SECRET"],
    capabilities: ["users", "sessions"],
    interactive: false,
    official: true,
  },
  {
    id: "clerk",
    name: "Clerk",
    description: "Add authentication, organizations, and billing",
    category: "auth",
    envVars: ["CLERK_SECRET_KEY"],
    capabilities: ["users", "orgs", "sessions"],
    interactive: false,
    official: true,
  },
  {
    id: "kubernetes",
    name: "Kubernetes MCP Server",
    description: "MCP server for interacting with Kubernetes clusters via kubectl",
    category: "devops",
    envVars: ["KUBECONFIG"],
    capabilities: ["pods", "services", "deployments"],
    interactive: false,
    official: true,
  },
  {
    id: "grafana",
    name: "Grafana MCP Server",
    description: "An MCP server giving access to Grafana dashboards, datasources, alerting, and more",
    category: "monitoring",
    envVars: ["GRAFANA_TOKEN", "GRAFANA_URL"],
    capabilities: ["dashboards", "alerts"],
    interactive: false,
    official: true,
  },
  {
    id: "honeycomb",
    name: "Honeycomb",
    description: "Query and explore observability data and SLOs",
    category: "monitoring",
    envVars: ["HONEYCOMB_API_KEY"],
    capabilities: ["query", "traces", "slos"],
    interactive: false,
    official: true,
  },
  {
    id: "dynatrace",
    name: "Dynatrace MCP Server",
    description: "Access Dynatrace observability data: logs, metrics, problems, vulnerabilities",
    category: "monitoring",
    envVars: ["DT_API_TOKEN", "DT_ENV_URL"],
    capabilities: ["logs", "metrics", "problems"],
    interactive: false,
    official: true,
  },
  {
    id: "instana",
    name: "MCP Instana Server",
    description: "MCP Instana Server for Observability",
    category: "monitoring",
    envVars: ["INSTANA_API_TOKEN"],
    capabilities: ["traces", "alerts"],
    interactive: false,
    official: false,
  },
  {
    id: "socket",
    name: "Socket",
    description: "Socket MCP server for scanning dependencies",
    category: "security",
    envVars: ["SOCKET_API_KEY"],
    capabilities: ["scan", "alerts"],
    interactive: false,
    official: true,
  },
  {
    id: "aws",
    name: "AWS API MCP Server",
    description: "Manage AWS resources using AWS CLI commands",
    category: "devops",
    envVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
    capabilities: ["ec2", "s3", "lambda", "rds"],
    interactive: false,
    official: true,
  },
  {
    id: "gce",
    name: "Google Compute Engine",
    description: "MCP server for Google Compute Engine",
    category: "devops",
    envVars: ["GOOGLE_APPLICATION_CREDENTIALS"],
    capabilities: ["instances", "disks"],
    interactive: false,
    official: true,
  },
  {
    id: "panos",
    name: "PanOS MCP",
    description: "Manage Palo Alto Networks firewalls with 70+ tools",
    category: "security",
    envVars: ["PANOS_HOSTNAME", "PANOS_API_KEY"],
    capabilities: ["policies", "logs", "config"],
    interactive: false,
    official: true,
  },
  {
    id: "zscaler",
    name: "Zscaler MCP Server",
    description: "AI-powered management of Zscaler Zero Trust Exchange services",
    category: "security",
    envVars: ["ZSCALER_CLIENT_ID", "ZSCALER_SECRET"],
    capabilities: ["zia", "zpa", "zdx"],
    interactive: false,
    official: true,
  },
  {
    id: "growthbook",
    name: "GrowthBook",
    description: "Open source feature flagging and experimentation platform",
    category: "devops",
    envVars: ["GROWTHBOOK_API_KEY"],
    capabilities: ["features", "experiments"],
    interactive: false,
    official: true,
  },

  // ============================================
  // DESIGN & CREATIVITY
  // ============================================
  {
    id: "figma",
    name: "Figma",
    description: "Pull in Figma context and generate high-quality code",
    category: "design",
    envVars: ["FIGMA_ACCESS_TOKEN"],
    capabilities: ["files", "components", "code"],
    interactive: true,
    official: true,
  },
  {
    id: "canva",
    name: "Canva",
    description: "Search, create, autofill, and export Canva designs",
    category: "design",
    envVars: ["CANVA_API_KEY"],
    capabilities: ["designs", "templates"],
    interactive: true,
    official: true,
  },
  {
    id: "miro",
    name: "Miro",
    description: "Access and create new content on Miro boards",
    category: "design",
    envVars: ["MIRO_ACCESS_TOKEN"],
    capabilities: ["boards", "cards", "widgets"],
    interactive: true,
    official: true,
  },
  {
    id: "tldraw",
    name: "tldraw",
    description: "Let Claude sketch, draw, and diagram with you",
    category: "design",
    envVars: [],
    capabilities: ["draw", "diagram"],
    interactive: true,
    official: true,
  },
  {
    id: "excalidraw",
    name: "Excalidraw",
    description: "MCP for creating interactive hand-drawn diagrams",
    category: "design",
    envVars: [],
    capabilities: ["draw", "diagram"],
    interactive: true,
    official: true,
  },
  {
    id: "mermaid",
    name: "Mermaid Chart",
    description: "Validates Mermaid syntax, renders diagrams as SVG",
    category: "design",
    envVars: [],
    capabilities: ["diagrams", "validation"],
    interactive: true,
    official: true,
  },
  {
    id: "lucid",
    name: "Lucid",
    description: "Ideate, diagram, and align teams",
    category: "design",
    envVars: ["LUCID_API_KEY"],
    capabilities: ["diagrams", "spark"],
    interactive: true,
    official: true,
  },
  {
    id: "sketch",
    name: "Sketch",
    description: "Explore designs, organize documents, generate code, export assets",
    category: "design",
    envVars: ["SKETCH_TOKEN"],
    capabilities: ["designs", "assets"],
    interactive: false,
    official: true,
  },
  {
    id: "gamma",
    name: "Gamma",
    description: "Create presentations, docs, socials, and sites with AI",
    category: "productivity",
    envVars: ["GAMMA_API_KEY"],
    capabilities: ["presentations", "docs"],
    interactive: true,
    official: true,
  },
  {
    id: "magic-patterns",
    name: "Magic Patterns",
    description: "Discuss and iterate on Magic Patterns designs",
    category: "design",
    envVars: ["MAGIC_PATTERNS_API_KEY"],
    capabilities: ["designs"],
    interactive: false,
    official: true,
  },
  {
    id: "theme-factory",
    name: "Theme Factory",
    description: "Style artifacts with themes for slides, docs, HTML pages",
    category: "design",
    envVars: [],
    capabilities: ["themes", "styling"],
    interactive: false,
    official: false,
  },

  // ============================================
  // FINANCE
  // ============================================
  {
    id: "stripe",
    name: "Stripe",
    description: "Payment processing and financial infrastructure tools",
    category: "finance",
    envVars: ["STRIPE_SECRET_KEY"],
    capabilities: ["payments", "customers", "subscriptions"],
    interactive: true,
    official: true,
  },
  {
    id: "paypal",
    name: "PayPal",
    description: "Access PayPal payments platform",
    category: "finance",
    envVars: ["PAYPAL_CLIENT_ID", "PAYPAL_SECRET"],
    capabilities: ["payments", "invoices"],
    interactive: true,
    official: true,
  },
  {
    id: "square",
    name: "Square",
    description: "Search and manage transaction, merchant, and payment data",
    category: "finance",
    envVars: ["SQUARE_ACCESS_TOKEN"],
    capabilities: ["payments", "orders"],
    interactive: false,
    official: true,
  },
  {
    id: "razorpay",
    name: "Razorpay",
    description: "Turn Claude into your Razorpay Dashboard Assistant",
    category: "finance",
    envVars: ["RAZORPAY_KEY_ID", "RAZORPAY_KEY_SECRET"],
    capabilities: ["payments", "orders"],
    interactive: false,
    official: true,
  },
  {
    id: "gocardless",
    name: "GoCardless",
    description: "Build GoCardless payment API integrations",
    category: "finance",
    envVars: ["GOCARDLESS_TOKEN"],
    capabilities: ["payments", "mandates"],
    interactive: false,
    official: true,
  },
  {
    id: "brex",
    name: "Brex",
    description: "Intelligent finance automation",
    category: "finance",
    envVars: ["BREX_TOKEN"],
    capabilities: ["transactions", "cards"],
    interactive: true,
    official: true,
  },
  {
    id: "mercury",
    name: "Mercury",
    description: "Search, analyze and understand your finances on Mercury",
    category: "finance",
    envVars: ["MERCURY_API_KEY"],
    capabilities: ["accounts", "transactions"],
    interactive: false,
    official: true,
  },
  {
    id: "ramp",
    name: "Ramp",
    description: "Search, access, and analyze your Ramp financial data",
    category: "finance",
    envVars: ["RAMP_TOKEN"],
    capabilities: ["transactions", "cards"],
    interactive: false,
    official: true,
  },
  {
    id: "quickbooks",
    name: "Intuit QuickBooks",
    description: "Business Finances made simple",
    category: "finance",
    envVars: ["QUICKBOOKS_TOKEN"],
    capabilities: ["invoices", "expenses"],
    interactive: true,
    official: true,
  },
  {
    id: "turbtax",
    name: "Intuit TurboTax",
    description: "Estimate tax refunds and connect with live tax experts",
    category: "finance",
    envVars: ["TURBOTAX_TOKEN"],
    capabilities: ["tax"],
    interactive: true,
    official: true,
  },
  {
    id: "credit-karma",
    name: "Intuit Credit Karma",
    description: "Credit score factors & insights",
    category: "finance",
    envVars: [],
    capabilities: ["credit"],
    interactive: true,
    official: true,
  },
  {
    id: "column-tax",
    name: "Aiwyn Tax (formerly Column Tax)",
    description: "Prepare your federal & state tax return 100% accurately",
    category: "finance",
    envVars: ["COLUMN_TAX_API_KEY"],
    capabilities: ["tax"],
    interactive: false,
    official: true,
  },
  {
    id: "fiscal-ai",
    name: "Fiscal.ai",
    description: "Clean Public Equity Fundamental Data",
    category: "finance",
    envVars: ["FISCAL_API_KEY"],
    capabilities: ["data"],
    interactive: false,
    official: false,
  },
  {
    id: "zoho-books",
    name: "Zoho Books",
    description: "Zoho Books MCP for Smart Finance Ops",
    category: "finance",
    envVars: ["ZOHO_CLIENT_ID", "ZOHO_CLIENT_SECRET"],
    capabilities: ["invoices", "expenses"],
    interactive: false,
    official: true,
  },
  {
    id: "jaz-accounting",
    name: "Jaz Accounting",
    description: "Create invoices, record bills, reconcile banks, close books, compute taxes",
    category: "finance",
    envVars: ["JAZ_API_KEY"],
    capabilities: ["invoices", "bills", "reconciliation", "tax"],
    interactive: false,
    official: true,
  },

  // ============================================
  // ANALYTICS
  // ============================================
  {
    id: "posthog",
    name: "PostHog",
    description: "Query, analyze, and manage your PostHog insights",
    category: "analytics",
    envVars: ["POSTHOG_API_KEY"],
    capabilities: ["query", "insights"],
    interactive: true,
    official: true,
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Analyze, query, and manage your Mixpanel data",
    category: "analytics",
    envVars: ["MIXPANEL_API_KEY"],
    capabilities: ["query", "insights"],
    interactive: false,
    official: true,
  },
  {
    id: "amplitude",
    name: "Amplitude",
    description: "Search, access, and get insights on your Amplitude data",
    category: "analytics",
    envVars: ["AMPLITUDE_API_KEY"],
    capabilities: ["query", "charts"],
    interactive: true,
    official: true,
  },
  {
    id: "pigment",
    name: "Pigment",
    description: "Analyze business data",
    category: "analytics",
    envVars: ["PIGMENT_TOKEN"],
    capabilities: ["query"],
    interactive: false,
    official: true,
  },
  {
    id: "similarweb",
    name: "Similarweb",
    description: "Real time web, mobile app, and market data",
    category: "analytics",
    envVars: ["SIMILARWEB_API_KEY"],
    capabilities: ["traffic", "market"],
    interactive: false,
    official: true,
  },
  {
    id: "visier",
    name: "Visier",
    description: "Find people, productivity and business impact insights",
    category: "analytics",
    envVars: ["VISIER_TOKEN"],
    capabilities: ["people", "productivity"],
    interactive: false,
    official: true,
  },
  {
    id: "omni-analytics",
    name: "Omni Analytics",
    description: "Query your data using natural language",
    category: "analytics",
    envVars: ["OMNI_TOKEN"],
    capabilities: ["query"],
    interactive: false,
    official: true,
  },
  {
    id: "supermetrics",
    name: "Supermetrics",
    description: "Analyze marketing performance across 200+ platforms",
    category: "analytics",
    envVars: ["SUPERMETRICS_TOKEN"],
    capabilities: ["query"],
    interactive: false,
    official: true,
  },
  {
    id: "coupler",
    name: "Coupler.io",
    description: "Connect data from hundreds of data sources and apps",
    category: "data-platform",
    envVars: ["COUPLER_TOKEN"],
    capabilities: ["connectors"],
    interactive: false,
    official: true,
  },
  {
    id: "windsor",
    name: "Windsor.ai",
    description: "Connect 325+ marketing, analytics and CRM data sources",
    category: "analytics",
    envVars: ["WINDSOR_API_KEY"],
    capabilities: ["query"],
    interactive: false,
    official: true,
  },
  {
    id: "pendo",
    name: "Pendo",
    description: "Connect to Pendo for product and user insights",
    category: "analytics",
    envVars: ["PENDO_API_KEY"],
    capabilities: ["insights"],
    interactive: false,
    official: true,
  },
  {
    id: "gainsight",
    name: "Gainsight (Staircase AI)",
    description: "Power AI Workflows with Customer Context",
    category: "analytics",
    envVars: ["GAINSIGHT_TOKEN"],
    capabilities: ["customer-context"],
    interactive: false,
    official: true,
  },
  {
    id: "pylon",
    name: "Pylon",
    description: "Search and manage Pylon support issues",
    category: "support",
    envVars: ["PYLON_TOKEN"],
    capabilities: ["tickets"],
    interactive: false,
    official: true,
  },
  {
    id: "zoho-desk",
    name: "Zoho Desk",
    description: "Zoho Desk MCP for Customer Support Automation",
    category: "support",
    envVars: ["ZOHO_CLIENT_ID", "ZOHO_CLIENT_SECRET"],
    capabilities: ["tickets"],
    interactive: false,
    official: true,
  },

  // ============================================
  // SEARCH & RESEARCH
  // ============================================
  {
    id: "tavily",
    name: "Tavily",
    description: "Connect your AI agents to the web",
    category: "search",
    envVars: ["TAVILY_API_KEY"],
    capabilities: ["web-search"],
    interactive: false,
    official: true,
  },
  {
    id: "exa",
    name: "Exa",
    description: "Web Search + Code Docs Search",
    category: "search",
    envVars: ["EXA_API_KEY"],
    capabilities: ["web-search", "code-search"],
    interactive: false,
    official: true,
  },
  {
    id: "g2",
    name: "G2",
    description: "Bring real buyer signals into AI workflows",
    category: "research",
    envVars: ["G2_API_KEY"],
    capabilities: ["reviews"],
    interactive: false,
    official: true,
  },
  {
    id: "cb-insights",
    name: "CB Insights",
    description: "Predictive intelligence on private companies",
    category: "research",
    envVars: ["CB_INSIGHTS_TOKEN"],
    capabilities: ["company-data"],
    interactive: false,
    official: true,
  },
  {
    id: "pitchbook",
    name: "PitchBook Premium",
    description: "PitchBook data, embedded in the way you work",
    category: "research",
    envVars: ["PITCHBOOK_TOKEN"],
    capabilities: ["company-data"],
    interactive: false,
    official: true,
  },
  {
    id: "lunarcrush",
    name: "LunarCrush",
    description: "Add real-time social media data to your searches",
    category: "research",
    envVars: ["LUNARCRUSH_API_KEY"],
    capabilities: ["social-data"],
    interactive: false,
    official: true,
  },
  {
    id: "quartr",
    name: "Quartr",
    description: "Financial data and AI infrastructure for company research",
    category: "research",
    envVars: ["QUARTR_TOKEN"],
    capabilities: ["financial-data"],
    interactive: false,
    official: true,
  },
  {
    id: "bigdata",
    name: "Bigdata.com",
    description: "Access real-time financial data",
    category: "research",
    envVars: ["BIGDATA_TOKEN"],
    capabilities: ["financial-data"],
    interactive: false,
    official: true,
  },
  {
    id: "factset",
    name: "FactSet AI-Ready Data",
    description: "Access institutional-quality financial data and analytics",
    category: "research",
    envVars: ["FACTSET_TOKEN"],
    capabilities: ["financial-data"],
    interactive: false,
    official: true,
  },
  {
    id: "lseg",
    name: "LSEG",
    description: "Access best in class data & analytics across asset classes",
    category: "research",
    envVars: ["LSEG_TOKEN"],
    capabilities: ["financial-data"],
    interactive: false,
    official: true,
  },
  {
    id: "msci",
    name: "MSCI",
    description: "Turn data into insight",
    category: "research",
    envVars: ["MSCI_TOKEN"],
    capabilities: ["analytics"],
    interactive: false,
    official: true,
  },
  {
    id: "morningstar",
    name: "Morningstar",
    description: "Up-to-date investment and market insights",
    category: "research",
    envVars: ["MORNINGSTAR_TOKEN"],
    capabilities: ["market-data"],
    interactive: false,
    official: true,
  },
  {
    id: "moodys",
    name: "Moody's",
    description: "Risk insights, analytics, and decision intelligence",
    category: "research",
    envVars: ["MOODYS_TOKEN"],
    capabilities: ["risk"],
    interactive: false,
    official: true,
  },
  {
    id: "sp-global",
    name: "S&P Global",
    description: "Query a range of S&P Global datasets",
    category: "research",
    envVars: ["SP_TOKEN"],
    capabilities: ["financial-data"],
    interactive: false,
    official: true,
  },
  {
    id: "daloopa",
    name: "Daloopa",
    description: "Financial fundamental data and KPIs with hyperlinks",
    category: "research",
    envVars: ["DALOOPA_TOKEN"],
    capabilities: ["financial-data"],
    interactive: false,
    official: true,
  },
  {
    id: "aura",
    name: "Aura",
    description: "Company intelligence & workforce analytics",
    category: "research",
    envVars: ["AURA_TOKEN"],
    capabilities: ["company-data"],
    interactive: false,
    official: true,
  },
  {
    id: "sprouts",
    name: "Sprouts Data Intelligence",
    description: "From query to qualified lead in seconds",
    category: "research",
    envVars: ["SPROUTS_TOKEN"],
    capabilities: ["leads"],
    interactive: false,
    official: true,
  },
  {
    id: "harmonic",
    name: "Harmonic",
    description: "Discover, research, and enrich companies and people",
    category: "research",
    envVars: ["HARMONIC_TOKEN"],
    capabilities: ["enrichment"],
    interactive: false,
    official: true,
  },
  {
    id: "clay",
    name: "Clay",
    description: "Find prospects. Research accounts. Personalize outreach",
    category: "sales",
    envVars: ["CLAY_API_KEY"],
    capabilities: ["prospects", "enrichment"],
    interactive: true,
    official: true,
  },
  {
    id: "vibe-prospecting",
    name: "Vibe Prospecting",
    description: "Find company & contact data",
    category: "sales",
    envVars: ["VIBE_TOKEN"],
    capabilities: ["leads"],
    interactive: false,
    official: true,
  },

  // ============================================
  // KNOWLEDGE & DOCUMENTS
  // ============================================
  {
    id: "notion",
    name: "Notion",
    description: "Connect your Notion workspace to search, update, and power workflows",
    category: "knowledge",
    envVars: ["NOTION_TOKEN"],
    capabilities: ["pages", "databases", "search"],
    interactive: true,
    official: true,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Find and analyze files instantly",
    category: "storage",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"],
    capabilities: ["files", "search"],
    interactive: true,
    official: true,
  },
  {
    id: "box",
    name: "Box",
    description: "Search, access and get insights on your Box content",
    category: "storage",
    envVars: ["BOX_TOKEN"],
    capabilities: ["files", "search"],
    interactive: true,
    official: true,
  },
  {
    id: "egnyte",
    name: "Egnyte",
    description: "Securely access and analyze Egnyte content",
    category: "storage",
    envVars: ["EGNYTE_TOKEN"],
    capabilities: ["files"],
    interactive: false,
    official: true,
  },
  {
    id: "guru",
    name: "Guru",
    description: "Search and interact with your company knowledge",
    category: "knowledge",
    envVars: ["GURU_TOKEN"],
    capabilities: ["search", "cards"],
    interactive: false,
    official: true,
  },
  {
    id: "glean",
    name: "Glean",
    description: "Bring enterprise context to Claude and your AI tools",
    category: "knowledge",
    envVars: ["GLEAN_TOKEN"],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "context7",
    name: "Context7",
    description: "Up-to-date docs for LLMs and AI code editors",
    category: "knowledge",
    envVars: [],
    capabilities: ["docs"],
    interactive: false,
    official: true,
  },
  {
    id: "mem",
    name: "Mem",
    description: "The AI notebook for everything on your mind",
    category: "knowledge",
    envVars: ["MEM_TOKEN"],
    capabilities: ["notes"],
    interactive: false,
    official: true,
  },
  {
    id: "craft",
    name: "Craft",
    description: "Notes & second brain",
    category: "knowledge",
    envVars: ["CRAFT_TOKEN"],
    capabilities: ["docs"],
    interactive: true,
    official: true,
  },
  {
    id: "granola",
    name: "Granola",
    description: "The AI notepad for meetings",
    category: "productivity",
    envVars: ["GRANOLA_TOKEN"],
    capabilities: ["notes"],
    interactive: false,
    official: true,
  },
  {
    id: "fellow",
    name: "Fellow.ai",
    description: "Chat with your meetings to uncover actionable insights",
    category: "productivity",
    envVars: ["FELLOW_TOKEN"],
    capabilities: ["meetings"],
    interactive: false,
    official: true,
  },
  {
    id: "krisp",
    name: "Krisp",
    description: "Add your meetings context via transcripts and notes",
    category: "productivity",
    envVars: ["KRISP_TOKEN"],
    capabilities: ["transcripts"],
    interactive: false,
    official: true,
  },
  {
    id: "fireflies",
    name: "Fireflies",
    description: "Analyze and generate insights from meeting transcripts",
    category: "productivity",
    envVars: ["FIREFLIES_TOKEN"],
    capabilities: ["transcripts"],
    interactive: false,
    official: true,
  },
  {
    id: "metaview",
    name: "Metaview",
    description: "The AI platform for recruiting",
    category: "hr",
    envVars: ["METAVIEW_TOKEN"],
    capabilities: ["interviews"],
    interactive: false,
    official: true,
  },
  {
    id: "meetgeek",
    name: "MeetGeek",
    description: "Manage meetings, transcripts, highlights, and insights",
    category: "productivity",
    envVars: ["MEETGEEK_TOKEN"],
    capabilities: ["meetings", "transcripts"],
    interactive: false,
    official: true,
  },
  {
    id: "circleback",
    name: "Circleback",
    description: "Search and access context from meetings",
    category: "productivity",
    envVars: ["CIRCLEBACK_TOKEN"],
    capabilities: ["meetings"],
    interactive: false,
    official: true,
  },

  // ============================================
  // HEALTHCARE & BIOTECH
  // ============================================
  {
    id: "pubmed",
    name: "PubMed",
    description: "Search biomedical literature from PubMed",
    category: "healthcare",
    envVars: [],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "biorxiv",
    name: "bioRxiv",
    description: "Access bioRxiv and medRxiv preprint data",
    category: "biotech",
    envVars: [],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "chembl",
    name: "ChEMBL",
    description: "Access the ChEMBL Database",
    category: "biotech",
    envVars: [],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "clinical-trials",
    name: "Clinical Trials",
    description: "Access ClinicalTrials.gov data",
    category: "healthcare",
    envVars: [],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "icd10",
    name: "ICD-10 Codes",
    description: "Access ICD-10-CM and ICD-10-PCS code sets",
    category: "healthcare",
    envVars: [],
    capabilities: ["codes"],
    interactive: false,
    official: true,
  },
  {
    id: "npi-registry",
    name: "NPI Registry",
    description: "Access US National Provider Identifier (NPI) Registry",
    category: "healthcare",
    envVars: [],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "consensus",
    name: "Consensus",
    description: "Explore scientific research",
    category: "research",
    envVars: [],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "scholar-gateway",
    name: "Scholar Gateway",
    description: "Enhance responses with scholarly research and citations",
    category: "research",
    envVars: [],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "benchling",
    name: "Benchling",
    description: "Connect to R&D data, source experiments, and notebooks",
    category: "biotech",
    envVars: ["BENCHLING_TOKEN"],
    capabilities: ["experiments"],
    interactive: true,
    official: true,
  },
  {
    id: "biorender",
    name: "BioRender",
    description: "Search for and use scientific templates and icons",
    category: "biotech",
    envVars: ["BIORENDER_TOKEN"],
    capabilities: ["templates"],
    interactive: false,
    official: true,
  },
  {
    id: "owkin",
    name: "Owkin",
    description: "Interact with AI agents built for biology",
    category: "biotech",
    envVars: ["OWKIN_TOKEN"],
    capabilities: ["biology"],
    interactive: false,
    official: true,
  },
  {
    id: "synapse",
    name: "Synapse.org",
    description: "Search and metadata tools for Synapse scientific data",
    category: "biotech",
    envVars: ["SYNAPSE_TOKEN"],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "open-targets",
    name: "Open Targets",
    description: "Drug target discovery and prioritisation platform",
    category: "biotech",
    envVars: [],
    capabilities: ["search"],
    interactive: false,
    official: true,
  },
  {
    id: "pophive",
    name: "PopHIVE Public Health Data",
    description: "Access near real-time public health data",
    category: "healthcare",
    envVars: [],
    capabilities: ["dashboards"],
    interactive: false,
    official: true,
  },
  {
    id: "10x-genomics",
    name: "10x Genomics Cloud",
    description: "Interact with 10x Genomics Cloud platform",
    category: "biotech",
    envVars: ["GENOMICS_TOKEN"],
    capabilities: ["analysis"],
    interactive: false,
    official: true,
  },
  {
    id: "enrichr",
    name: "Enrichr MCP Server",
    description: "Gene set enrichment analysis using Enrichr API",
    category: "biotech",
    envVars: [],
    capabilities: ["enrichment"],
    interactive: false,
    official: true,
  },

  // ============================================
  // LEGAL
  // ============================================
  {
    id: "harvey",
    name: "Harvey",
    description: "Answer legal queries, search vaults, and research",
    category: "legal",
    envVars: ["HARVEY_TOKEN"],
    capabilities: ["research"],
    interactive: false,
    official: true,
  },
  {
    id: "midpage",
    name: "Midpage Legal Research",
    description: "Conduct legal research and create work product",
    category: "legal",
    envVars: ["MIDPAGE_TOKEN"],
    capabilities: ["research"],
    interactive: false,
    official: true,
  },
  {
    id: "docusign",
    name: "Docusign",
    description: "Intelligent, secure contract management by Docusign",
    category: "legal",
    envVars: ["DOCUSIGN_TOKEN"],
    capabilities: ["envelopes"],
    interactive: true,
    official: true,
  },
  {
    id: "docuseal",
    name: "DocuSeal",
    description: "Sign, send & manage documents with DocuSeal",
    category: "legal",
    envVars: ["DOCUSEAL_TOKEN"],
    capabilities: ["documents"],
    interactive: false,
    official: true,
  },
  {
    id: "signnow",
    name: "SignNow",
    description: "Automate eSignature workflows directly from Claude",
    category: "legal",
    envVars: ["SIGNNOW_TOKEN"],
    capabilities: ["documents"],
    interactive: false,
    official: true,
  },
  {
    id: "signwell",
    name: "SignWell",
    description: "Create, send, track, and manage documents and templates",
    category: "legal",
    envVars: ["SIGNWELL_TOKEN"],
    capabilities: ["documents"],
    interactive: false,
    official: true,
  },
  {
    id: "legalzoom",
    name: "LegalZoom",
    description: "Attorney guidance & tools for business & personal needs",
    category: "legal",
    envVars: ["LEGALZOOM_TOKEN"],
    capabilities: ["business"],
    interactive: false,
    official: true,
  },

  // ============================================
  // BLOCKCHAIN
  // ============================================
  {
    id: "blockscout",
    name: "Blockscout",
    description: "Access and analyze blockchain data",
    category: "blockchain",
    envVars: ["BLOCKSCOUT_API_KEY"],
    capabilities: ["transactions", "blocks"],
    interactive: false,
    official: true,
  },
  {
    id: "crypto-com",
    name: "Crypto.com",
    description: "Real time prices, orders, charts, and more for crypto",
    category: "blockchain",
    envVars: ["CRYPTO_API_KEY"],
    capabilities: ["prices", "orders"],
    interactive: false,
    official: true,
  },
  {
    id: "blockchain-query",
    name: "BlockchainQuery",
    description: "Free blockchain data access across 60+ networks",
    category: "blockchain",
    envVars: [],
    capabilities: ["balances", "transactions", "tokens"],
    interactive: false,
    official: true,
  },

  // ============================================
  // EVENTS & TRAVEL
  // ============================================
  {
    id: "ticket-tailor",
    name: "Ticket Tailor",
    description: "Event platform for managing tickets, orders & more",
    category: "events",
    envVars: ["TICKET_TAILOR_TOKEN"],
    capabilities: ["events", "orders"],
    interactive: false,
    official: true,
  },
  {
    id: "fever",
    name: "Fever Event Discovery",
    description: "Discover live entertainment events worldwide",
    category: "events",
    envVars: ["FEVER_TOKEN"],
    capabilities: ["events"],
    interactive: false,
    official: true,
  },
  {
    id: "calendly",
    name: "Calendly",
    description: "Manage event types, availability, and bookings",
    category: "events",
    envVars: ["CALENDLY_TOKEN"],
    capabilities: ["events", "availability"],
    interactive: false,
    official: true,
  },
  {
    id: "kiwi",
    name: "Kiwi.com",
    description: "Search flights in Claude",
    category: "travel",
    envVars: ["KIWI_TOKEN"],
    capabilities: ["flights"],
    interactive: false,
    official: true,
  },
  {
    id: "lastminute",
    name: "lastminute.com",
    description: "Search, compare and book flights and hotels",
    category: "travel",
    envVars: ["LASTMINUTE_TOKEN"],
    capabilities: ["flights", "hotels"],
    interactive: false,
    official: true,
  },
  {
    id: "trivago",
    name: "Trivago",
    description: "Find your ideal hotel at the best price",
    category: "travel",
    envVars: ["TRIVAGO_TOKEN"],
    capabilities: ["hotels"],
    interactive: false,
    official: true,
  },
  {
    id: "directbooker",
    name: "DirectBooker",
    description: "Compare hotels, then book direct",
    category: "travel",
    envVars: ["DIRECTBOOKER_TOKEN"],
    capabilities: ["hotels"],
    interactive: false,
    official: true,
  },
  {
    id: "wyndham",
    name: "Wyndham Hotels and Resorts",
    description: "Discover the right Wyndham Hotel for you, faster",
    category: "travel",
    envVars: ["WYNDHAM_TOKEN"],
    capabilities: ["hotels"],
    interactive: false,
    official: true,
  },

  // ============================================
  // MUSIC & MEDIA
  // ============================================
  {
    id: "melon",
    name: "Melon",
    description: "Browse music charts & your personalized music picks",
    category: "music",
    envVars: [],
    capabilities: ["charts"],
    interactive: false,
    official: true,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Access the Hugging Face Hub and thousands of Gradio Apps",
    category: "ai-ml",
    envVars: ["HF_TOKEN"],
    capabilities: ["models", "datasets", "spaces"],
    interactive: true,
    official: true,
  },
  {
    id: "cloudinary",
    name: "Cloudinary",
    description: "Manage, transform and deliver your images & videos",
    category: "media",
    envVars: ["CLOUDINARY_API_KEY", "CLOUDINARY_API_SECRET"],
    capabilities: ["upload", "transform"],
    interactive: false,
    official: true,
  },

  // ============================================
  // HR
  // ============================================
  {
    id: "indeed",
    name: "Indeed",
    description: "Search for jobs on Indeed",
    category: "hr",
    envVars: ["INDEED_API_KEY"],
    capabilities: ["jobs"],
    interactive: false,
    official: true,
  },
  {
    id: "dice",
    name: "Dice",
    description: "Find active tech jobs on Dice",
    category: "hr",
    envVars: ["DICE_TOKEN"],
    capabilities: ["jobs"],
    interactive: false,
    official: true,
  },
  {
    id: "udemy",
    name: "Udemy Business",
    description: "Search and explore skill-building resources",
    category: "hr",
    envVars: ["UDEMY_TOKEN"],
    capabilities: ["courses"],
    interactive: false,
    official: true,
  },
  {
    id: "learning-commons",
    name: "Learning Commons Knowledge Graph",
    description: "K-12 standards, skills, and learning progressions",
    category: "hr",
    envVars: [],
    capabilities: ["standards"],
    interactive: false,
    official: true,
  },

  // ============================================
  // OTHER
  // ============================================
  {
    id: "tango",
    name: "Tango",
    description: "Search for US Government Contracting Data",
    category: "government",
    envVars: ["TANGO_TOKEN"],
    capabilities: ["contracts"],
    interactive: false,
    official: true,
  },
  {
    id: "benevity",
    name: "Benevity",
    description: "Find and engage with verified nonprofits",
    category: "research",
    envVars: ["BENEVITY_TOKEN"],
    capabilities: ["nonprofits"],
    interactive: false,
    official: true,
  },
  {
    id: "candid",
    name: "Candid",
    description: "Research nonprofits and funders using Candid's data",
    category: "research",
    envVars: ["CANDID_TOKEN"],
    capabilities: ["nonprofits"],
    interactive: false,
    official: true,
  },
  {
    id: "granted",
    name: "Granted",
    description: "Discover every grant opportunity in existence",
    category: "research",
    envVars: ["GRANTED_TOKEN"],
    capabilities: ["grants"],
    interactive: false,
    official: true,
  },
  {
    id: "chronograph",
    name: "Chronograph",
    description: "Interact with your Chronograph data directly in Claude",
    category: "productivity",
    envVars: ["CHRONOGRAPH_TOKEN"],
    capabilities: ["time"],
    interactive: false,
    official: true,
  },
  {
    id: "intapp",
    name: "Intapp Celeste",
    description: "Securely, compliantly access Intapp Celeste products",
    category: "legal",
    envVars: ["INTAPP_TOKEN"],
    capabilities: ["data"],
    interactive: false,
    official: true,
  },
  {
    id: "clarity-ai",
    name: "Clarity AI",
    description: "Simulate fund classifications under proposed SFDR 2.0",
    category: "finance",
    envVars: ["CLARITY_TOKEN"],
    capabilities: ["funds"],
    interactive: false,
    official: true,
  },
  {
    id: "day-ai",
    name: "Day AI",
    description: "Know everything about your prospects & customers with CRMx",
    category: "sales",
    envVars: ["DAY_AI_TOKEN"],
    capabilities: ["prospects"],
    interactive: false,
    official: true,
  },
  {
    id: "jotform",
    name: "Jotform",
    description: "Create forms & analyze submissions inside Claude",
    category: "productivity",
    envVars: ["JOTFORM_TOKEN"],
    capabilities: ["forms"],
    interactive: true,
    official: true,
  },
  {
    id: "godaddy",
    name: "GoDaddy",
    description: "Search domains and check availability",
    category: "hosting",
    envVars: ["GODADDY_TOKEN"],
    capabilities: ["domains"],
    interactive: false,
    official: true,
  },
  {
    id: "bitly",
    name: "Bitly",
    description: "Shorten links, generate QR Codes, and track performance",
    category: "marketing",
    envVars: ["BITLY_TOKEN"],
    capabilities: ["links"],
    interactive: false,
    official: true,
  },
  {
    id: "goodnotes",
    name: "Goodnotes",
    description: "Turn AI insights into documents",
    category: "productivity",
    envVars: ["GOODNOTES_TOKEN"],
    capabilities: ["documents"],
    interactive: true,
    official: true,
  },
  {
    id: "lumin",
    name: "Lumin",
    description: "Manage documents, send signature requests, and convert Markdown to PDF",
    category: "productivity",
    envVars: ["LUMIN_TOKEN"],
    capabilities: ["documents"],
    interactive: false,
    official: true,
  },
  {
    id: "mt-newswires",
    name: "MT Newswires",
    description: "Trusted real-time global financial news provider",
    category: "research",
    envVars: ["MT_TOKEN"],
    capabilities: ["news"],
    interactive: false,
    official: true,
  },
  {
    id: "enterpret",
    name: "Enterpret Wisdom",
    description: "Get answers from unified feedback of your customers",
    category: "analytics",
    envVars: ["ENTERPRET_TOKEN"],
    capabilities: ["feedback"],
    interactive: false,
    official: true,
  },
  {
    id: "cdata",
    name: "CData Connect AI",
    description: "Managed MCP platform for 350 sources",
    category: "data-platform",
    envVars: ["CDATA_TOKEN"],
    capabilities: ["connectors"],
    interactive: false,
    official: true,
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Bring your structured data to Claude",
    category: "data-platform",
    envVars: ["AIRTABLE_TOKEN"],
    capabilities: ["tables", "records"],
    interactive: true,
    official: true,
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    description: "Access SharePoint, OneDrive, Outlook, and Teams directly in Claude",
    category: "productivity",
    envVars: ["M365_TOKEN"],
    capabilities: ["sharepoint", "onedrive", "outlook"],
    interactive: true,
    official: true,
  },
  {
    id: "natoma",
    name: "Natoma",
    description: "Access all your internal tools, enterprise apps & data",
    category: "knowledge",
    envVars: ["NATOMA_TOKEN"],
    capabilities: ["tools"],
    interactive: false,
    official: true,
  },
  {
    id: "lorikeet",
    name: "Lorikeet",
    description: "A universal concierge for complex businesses",
    category: "productivity",
    envVars: ["LORIKEET_TOKEN"],
    capabilities: ["concierge"],
    interactive: false,
    official: true,
  },
  {
    id: "port-io",
    name: "Port IO",
    description: "Search your context lake and safely run actions",
    category: "knowledge",
    envVars: ["PORT_TOKEN"],
    capabilities: ["search", "actions"],
    interactive: false,
    official: true,
  },
  {
    id: "jentic",
    name: "Jentic",
    description: "One connection to access all your tools securely",
    category: "security",
    envVars: ["JENTIC_TOKEN"],
    capabilities: ["tools"],
    interactive: false,
    official: true,
  },
  {
    id: "playmcp",
    name: "PlayMCP",
    description: "Connect and use PlayMCP servers in your toolbox",
    category: "devops",
    envVars: [],
    capabilities: ["servers"],
    interactive: false,
    official: true,
  },
  {
    id: "data-grail",
    name: "DataGrail",
    description: "Secure, production-ready AI orchestration for privacy",
    category: "security",
    envVars: ["DATAGRAIL_TOKEN"],
    capabilities: ["privacy"],
    interactive: false,
    official: true,
  },
  {
    id: "crossbeam",
    name: "Crossbeam",
    description: "Explore partner data and ecosystem insights in Claude",
    category: "sales",
    envVars: ["CROSSBEAM_TOKEN"],
    capabilities: ["partners"],
    interactive: false,
    official: true,
  },
  {
    id: "common-room",
    name: "Common Room",
    description: "Turn Common Room into your GTM copilot",
    category: "sales",
    envVars: ["COMMONROOM_TOKEN"],
    capabilities: ["accounts"],
    interactive: true,
    official: true,
  },
  {
    id: "zocks",
    name: "Zocks",
    description: "Analyze client conversations, patterns, and insights",
    category: "analytics",
    envVars: ["ZOCKS_TOKEN"],
    capabilities: ["conversations"],
    interactive: false,
    official: true,
  },
  {
    id: "net-suite",
    name: "NetSuite",
    description: "Connect Claude to NetSuite data for analysis & insights",
    category: "finance",
    envVars: ["NETSUITE_TOKEN"],
    capabilities: ["data"],
    interactive: false,
    official: true,
  },
  {
    id: "plaid",
    name: "Plaid Developer Tools",
    description: "Monitor, debug, and optimize your Plaid integration",
    category: "finance",
    envVars: ["PLAID_TOKEN"],
    capabilities: ["debug"],
    interactive: false,
    official: true,
  },
  {
    id: "postman-minimal",
    name: "Postman MCP Server (Minimal)",
    description: "Connect your AI to your APIs on Postman",
    category: "code",
    envVars: ["POSTMAN_API_KEY"],
    capabilities: ["apis"],
    interactive: false,
    official: true,
  },
  {
    id: "aws-marketplace",
    name: "AWS Marketplace",
    description: "Discover, evaluate, and buy solutions for the cloud",
    category: "devops",
    envVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
    capabilities: ["products"],
    interactive: false,
    official: true,
  },
  {
    id: "apify",
    name: "Apify MCP server",
    description: "Extract data from any website using thousands of tools",
    category: "search",
    envVars: ["APIFY_TOKEN"],
    capabilities: ["scraping"],
    interactive: false,
    official: true,
  },
  {
    id: "pg-aiguide",
    name: "pg-aiguide",
    description: "Search pg and Tiger docs, learn database skills",
    category: "database",
    envVars: [],
    capabilities: ["docs"],
    interactive: false,
    official: true,
  },
  {
    id: "jam",
    name: "Jam",
    description: "Record screen and collect automatic context for issues",
    category: "support",
    envVars: ["JAM_TOKEN"],
    capabilities: ["recordings"],
    interactive: false,
    official: true,
  },
  {
    id: "sap-fiori",
    name: "SAP Fiori MCP Server",
    description: "Generate and adapt SAP Fiori elements applications",
    category: "code",
    envVars: ["SAP_TOKEN"],
    capabilities: ["apps"],
    interactive: false,
    official: true,
  },
  {
    id: "sapui5",
    name: "SAPUI5 MCP Server",
    description: "MCP server for SAPUI5/OpenUI5 development",
    category: "code",
    envVars: ["SAP_TOKEN"],
    capabilities: ["apps"],
    interactive: false,
    official: true,
  },
  {
    id: "sap-cap",
    name: "SAP CAP MCP Server",
    description: "AI-assisted development of SAP Cloud Application Programming Model",
    category: "code",
    envVars: ["SAP_TOKEN"],
    capabilities: ["cds"],
    interactive: false,
    official: true,
  },
  {
    id: "sap-mdk",
    name: "SAP MDK MCP Server",
    description: "AI-assisted development of SAP Mobile Development Kit",
    category: "code",
    envVars: ["SAP_TOKEN"],
    capabilities: ["mobile"],
    interactive: false,
    official: true,
  },
  {
    id: "braze",
    name: "Braze MCP Server",
    description: "Braze MCP Server for REST API Read-Only endpoints access",
    category: "marketing",
    envVars: ["BRAZE_TOKEN"],
    capabilities: ["campaigns"],
    interactive: false,
    official: true,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs Agents MCP App",
    description: "Create and manage ElevenLabs Agents with an interactive UI",
    category: "ai-ml",
    envVars: ["ELEVENLABS_API_KEY"],
    capabilities: ["voice-agents"],
    interactive: true,
    official: true,
  },
  {
    id: "stats-compass",
    name: "Stats Compass",
    description: "Multiple data science tools for data loading, cleaning, visualization, and ML workflows",
    category: "analytics",
    envVars: [],
    capabilities: ["data-science"],
    interactive: false,
    official: true,
  },
  {
    id: "tomba",
    name: "Tomba MCP Server",
    description: "MCP server for Tomba email finder and verification API",
    category: "email",
    envVars: ["TOMBA_TOKEN"],
    capabilities: ["email-finder"],
    interactive: false,
    official: true,
  },
  {
    id: "tomtom",
    name: "TomTom Maps MCP",
    description: "Provide real-time geospatial context from TomTom",
    category: "search",
    envVars: ["TOMTOM_TOKEN"],
    capabilities: ["maps", "routing"],
    interactive: false,
    official: true,
  },
  {
    id: "defense-com",
    name: "Defense.com Threat Analysis",
    description: "Access your Defense.com portal to view open threats",
    category: "security",
    envVars: ["DEFENSE_TOKEN"],
    capabilities: ["threats"],
    interactive: false,
    official: true,
  },
  {
    id: "miggo",
    name: "Miggo Public API MCP Server",
    description: "Query services, endpoints, vulnerabilities, findings, dependencies",
    category: "security",
    envVars: ["MIGGO_TOKEN"],
    capabilities: ["services"],
    interactive: false,
    official: true,
  },
  {
    id: "conviso",
    name: "Conviso MCP Server",
    description: "Expose Conviso Platform data to MCP clients",
    category: "security",
    envVars: ["CONVISO_TOKEN"],
    capabilities: ["projects", "issues"],
    interactive: false,
    official: true,
  },
  {
    id: "karp",
    name: "KARP Inspector Lite",
    description: "Semantic codebase search for Claude Desktop",
    category: "code",
    envVars: [],
    capabilities: ["code-search"],
    interactive: false,
    official: true,
  },
  {
    id: "pathmode",
    name: "Pathmode",
    description: "Connect AI agents to your Intent Layer",
    category: "devops",
    envVars: ["PATHMODE_TOKEN"],
    capabilities: ["context"],
    interactive: false,
    official: true,
  },
  {
    id: "vendr",
    name: "Vendr Software Pricing Tools",
    description: "Model Context Protocol tools for Vendr software pricing insights",
    category: "finance",
    envVars: ["VENDR_TOKEN"],
    capabilities: ["pricing"],
    interactive: false,
    official: true,
  },
  {
    id: "cloudglue",
    name: "Cloudglue",
    description: "Analyze, search, and extract structured data from video collections",
    category: "media",
    envVars: ["CLOUDGLUE_TOKEN"],
    capabilities: ["video"],
    interactive: false,
    official: true,
  },
  {
    id: "docling",
    name: "Docling MCP",
    description: "Document processing and analysis capabilities",
    category: "productivity",
    envVars: [],
    capabilities: ["documents"],
    interactive: false,
    official: true,
  },
  {
    id: "tooluniverse",
    name: "ToolUniverse",
    description: "An ecosystem for democratizing AI scientists with 600+ scientific tools",
    category: "research",
    envVars: [],
    capabilities: ["science"],
    interactive: false,
    official: true,
  },
  {
    id: "vybit",
    name: "Vybit Notifications",
    description: "Send push notifications with personalized sounds",
    category: "communication",
    envVars: ["VYBIT_TOKEN"],
    capabilities: ["notifications"],
    interactive: false,
    official: true,
  },
  {
    id: "lilt",
    name: "LILT",
    description: "High-quality translation with human verification",
    category: "communication",
    envVars: ["LILT_TOKEN"],
    capabilities: ["translation"],
    interactive: false,
    official: true,
  },
  {
    id: "ckan",
    name: "CKAN MCP Server",
    description: "Explore open data portals based on CKAN",
    category: "research",
    envVars: [],
    capabilities: ["data-portals"],
    interactive: false,
    official: true,
  },
  {
    id: "rt",
    name: "RT (Request Tracker)",
    description: "Search tickets, manage queues, add comments and replies",
    category: "support",
    envVars: ["RT_TOKEN"],
    capabilities: ["tickets"],
    interactive: false,
    official: true,
  },
  {
    id: "local-falcon",
    name: "Local Falcon",
    description: "AI visibility and local search intelligence platform",
    category: "marketing",
    envVars: ["LOCALFALCON_TOKEN"],
    capabilities: ["local-search"],
    interactive: false,
    official: true,
  },
  {
    id: "ahrefs",
    name: "Ahrefs",
    description: "SEO & AI search analytics",
    category: "marketing",
    envVars: ["AHREFS_TOKEN"],
    capabilities: ["seo"],
    interactive: false,
    official: true,
  },
  {
    id: "aiops",
    name: "AirOps",
    description: "Craft content that wins AI search",
    category: "marketing",
    envVars: ["AIOPS_TOKEN"],
    capabilities: ["content"],
    interactive: false,
    official: true,
  },
  {
    id: "base44",
    name: "Base44",
    description: "Build and manage Base44 apps",
    category: "code",
    envVars: ["BASE44_TOKEN"],
    capabilities: ["apps"],
    interactive: false,
    official: true,
  },
  {
    id: "airwallex",
    name: "Airwallex Developer",
    description: "Integrate with the Airwallex Platform using Claude",
    category: "finance",
    envVars: ["AIRWALLEX_TOKEN"],
    capabilities: ["payments"],
    interactive: false,
    official: true,
  },
  {
    id: "aura-security",
    name: "Aura",
    description: "Company intelligence & workforce analytics",
    category: "research",
    envVars: ["AURA_SECURITY_TOKEN"],
    capabilities: ["analytics"],
    interactive: false,
    official: true,
  },
];

/**
 * Get connectors by category
 */
export function getConnectorsByCategory(category: ConnectorCategory): ConnectorEntry[] {
  return ALL_CONNECTORS.filter(c => c.category === category);
}

/**
 * Search connectors by name
 */
export function searchConnectors(query: string): ConnectorEntry[] {
  const lower = query.toLowerCase();
  return ALL_CONNECTORS.filter(c =>
    c.name.toLowerCase().includes(lower) ||
    c.description.toLowerCase().includes(lower) ||
    c.category.toLowerCase().includes(lower)
  );
}

/**
 * Get configured connectors (those with env vars set)
 */
export function getConfiguredConnectors(): ConnectorEntry[] {
  return ALL_CONNECTORS.filter(c =>
    c.envVars.every(v => process.env[v] && process.env[v]!.length > 0)
  );
}

/**
 * Get connector MCP config
 */
export function getConnectorMCPConfig(connector: ConnectorEntry): any {
  if (!connector.mcpPackage) return null;

  return {
    name: connector.id,
    command: "npx",
    args: ["-y", connector.mcpPackage],
    env: connector.envVars.reduce((acc, v) => {
      acc[v] = process.env[v] || "";
      return acc;
    }, {} as Record<string, string>),
    timeout: 30000,
  };
}
